# def toliq_ism_yasa(ism,familyani,otasining_ism =''):
#   if otasining_ism:
#     toliq_ism =f'{ism}{familyani}{otasining_ism}'
#   else:
#     toliq_ism = f"{ism}{familyani}"
#     return toliq_ism
# talaba = toliq_ism_yasa('Dadaxon','Olimov')
# talaba2 =toliq_ism_yasa('Dadaxon',"zokir","Olimov")  
# print(f"darsga kelmaganlar {talaba} va {talaba2}")  
  #  range orqali ishlash
# def oraliq(min,max,qadam=''):
#   if oraliq:
#     sonlar = f"{min}{max}{qadam}"
#   else:
#     sonlar =f'{min}{max}'
#   sonlar =[]
#   while min<max:
#       sonlar.append(min) 
#       min +=1
#   return sonlar
# print(oraliq(10,20,2))  
# print(oraliq(12,22))






    
